[package]
name = "backup"
version = "0.1.0"
authors = ["Erlend Langseth <3rlendhl@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
iced = "0.2"
iced_native = "0.3"
iced_graphics = "0.1"
app_dirs = "1.2.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
